name: workflow_0 #
on: [push, workflow_dispatch]
jobs:
  github_action_context:  # Get an understanding of GitHub Context variables
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Ths job was automatically triggered by a ${{github.event_name}}.'
      - run: echo 'Job is running on a ${{runner.os}} server hosted by GitHub'
      - run: echo 'The branch is ${{github.ref}} and the repo is ${{github.repository}}'
   
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
           repository: yongshun950824/rs_policy_service_actions
           token: ${{ secrets.GITHUB_TOKEN }}  
  
      - run: echo 'The  ${{github.repository}} has been cloned to the runner.'
      - run: echo 'The workflow is now ready to test your code on the runner'
      - name: List files in the repository
        run: |
          ls ${{github.workspace}}
      - run: echo 'The job status is ${{job.status}}'    
